In [3]:
import pandas as pd
train = pd.read_csv('/content/drive/MyDrive/kaggle/store/train.csv')

In [4]:
train.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [5]:
'''
store_nbr : the store where the products are sold
family : type of product sold
sales : total sales
onpromotion : total number of items in a product family that were promoted at a store at a given date
'''

'\nstore_nbr : the store where the products are sold\nfamily : type of product sold\nsales : total sales\nonpromotion : total number of items in a product family that were promoted at a store at a given date\n'

In [7]:
test = pd.read_csv('/content/drive/MyDrive/kaggle/store/test.csv')

In [8]:
test.head()

        id        date  store_nbr      family  onpromotion
0  3000888  2017-08-16          1  AUTOMOTIVE            0
1  3000889  2017-08-16          1   BABY CARE            0
2  3000890  2017-08-16          1      BEAUTY            2
3  3000891  2017-08-16          1   BEVERAGES           20
4  3000892  2017-08-16          1       BOOKS            0

In [10]:
sample_submission = pd.read_csv('/content/drive/MyDrive/kaggle/store/sample_submission.csv')

In [11]:
sample_submission.head()

        id  sales
0  3000888    0.0
1  3000889    0.0
2  3000890    0.0
3  3000891    0.0
4  3000892    0.0

In [13]:
stores = pd.read_csv('/content/drive/MyDrive/kaggle/store/stores.csv')

In [14]:
stores.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [15]:
#cluster : grouping of similar stores

In [16]:
oil = pd.read_csv('/content/drive/MyDrive/kaggle/store/oil.csv')

In [17]:
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [18]:
holidays_events = pd.read_csv('/content/drive/MyDrive/kaggle/store/holidays_events.csv')

In [20]:
holidays_events.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [24]:
holidays_events[(holidays_events['description']=='Independencia de Guayaquil')]

,date,type,locale,locale_name,description,transferred
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
72,2013-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
135,2014-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
190,2015-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,False
274,2016-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,False
331,2017-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,False

In [25]:
holidays_events[holidays_events['type']=='Transfer']

,date,type,locale,locale_name,description,transferred
20,2012-10-12,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
73,2013-10-11,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
136,2014-10-10,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
256,2016-05-27,Transfer,National,Ecuador,Traslado Batalla de Pichincha,False
265,2016-07-24,Transfer,Local,Guayaquil,Traslado Fundacion de Guayaquil,False
269,2016-08-12,Transfer,National,Ecuador,Traslado Primer Grito de Independencia,False
298,2017-01-02,Transfer,National,Ecuador,Traslado Primer dia del ano,False
304,2017-04-13,Transfer,Local,Cuenca,Fundacion de Cuenca,False
313,2017-05-26,Transfer,National,Ecuador,Traslado Batalla de Pichincha,False
325,2017-08-11,Transfer,National,Ecuador,Traslado Primer Grito de Independencia,False
329,2017-09-29,Transfer,Local,Ibarra,Fundacion de Ibarra,False
342,2017-12-08,Transfer,Local,Quito,Traslado Fundacion de Quito,False

In [ ]:
'''
transferred : transferred day is more like a normal day than a holiday.
Real holiday is where the type is "Transfer"
'''

In [ ]:
transactions =