In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
import random
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [32]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(7) # Seed 고정

In [33]:
import pandas as pd
train = pd.read_csv('/content/drive/MyDrive/LG/train.csv')
test = pd.read_csv('/content/drive/MyDrive/LG/test.csv')

In [34]:
train=train.fillna(0)
test=test.fillna(0)

In [35]:
train_x = train.drop(columns=['PRODUCT_ID','Y_Class','Y_Quality','TIMESTAMP'])
test_x = test.drop(columns=['PRODUCT_ID','TIMESTAMP'])
train_x_num = train_x.filter(regex='X')
test_x_num = test_x.filter(regex='X')
#min-max-scaling이 더 나을듯
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(train_x_num)
train_x_num_scaled = scaler.transform(train_x_num)
test_x_num_scaled = scaler.transform(test_x_num)
train_x_num_scaled = pd.DataFrame(train_x_num_scaled)
test_x_num_scaled = pd.DataFrame(test_x_num_scaled)

In [36]:
train_x_num_scaled

,0,1,2,3,4,5,6,7,8,9,...,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874
0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.653054,0.595543,0.538984,0.568830,0.975172,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.645584,0.623653,0.727032,0.589688,0.909718,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.650564,0.533790,0.703029,0.609544,0.982445,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.626494,0.570492,0.863599,0.510262,0.900063,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.642430,0.610108,0.776858,0.552144,0.965141,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,0.019417,0.931373,0.0,1.0,0.909091,0.0,0.806452,0.909091,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
594,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.821215,0.772939,0.842410,0.919406,0.833730,1.0,0.0,0.0,0.0,0.0
595,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
596,0.388350,0.921569,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
597,0.203883,0.852941,0.0,1.0,0.909091,0.0,0.983871,0.909091,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

In [37]:
test_x_num_scaled

,0,1,2,3,4,5,6,7,8,9,...,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874
0,0.019417,0.921569,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.019417,0.911765,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.019417,0.931373,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,0.019417,0.892157,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
306,0.019417,0.941176,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
307,0.019417,0.892157,0.0,1.0,0.909091,0.0,0.806452,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
308,0.019417,0.931373,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309,0.019417,0.852941,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
cat_encoding = pd.get_dummies(train_x[['LINE','PRODUCT_CODE']])
cat_encoding_test = pd.get_dummies(test_x[['LINE','PRODUCT_CODE']])
train_x_prep = train_x_num_scaled.join(cat_encoding)
test_x_prep = test_x_num_scaled.join(cat_encoding_test)

In [39]:
train_x_prep.head()

,0,1,2,3,4,5,6,7,8,9,...,2874,LINE_T010305,LINE_T010306,LINE_T050304,LINE_T050307,LINE_T100304,LINE_T100306,PRODUCT_CODE_A_31,PRODUCT_CODE_O_31,PRODUCT_CODE_T_31
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,0,0,0,1,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,1,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,0,0,0,1,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,1,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,0,0,0,1,0,0

In [40]:
train_y = train[['Y_Quality','Y_Class']]

In [49]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(train_x_prep, train_y, test_size = 0.2, random_state = 7)

In [50]:
y_train_qual = y_train['Y_Quality']
y_val_qual = y_val['Y_Quality']
y_train_cl = y_train['Y_Class']
y_val_cl = y_val['Y_Class']

In [51]:
#RandomforestRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
rfr = RandomForestRegressor()
rfr.fit(x_train, y_train_qual)
rfr_pred = rfr.predict(x_val)
mae = mean_absolute_error(y_val_qual, rfr_pred)
mse = mean_squared_error(y_val_qual, rfr_pred)
print('MAE: %d' %mae)
print('MSE: %d' %mse)
print(r2_score(y_val_qual, rfr_pred))

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

MAE: 0
MSE: 0
0.6328395008975327

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [52]:
# train_class = pd.DataFrame(train['Y_Class'])
# train_qual = pd.DataFrame(train['Y_Quality'])
cq_rf = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))

<ipython-input-52-367135154b13>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  cq_rf = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))

In [53]:
cq_preds = cq_rf.predict(pd.DataFrame(rfr_pred))

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_val_cl, cq_preds))

              precision    recall  f1-score   support

           0       0.86      0.33      0.48        18
           1       0.78      0.97      0.87        76
           2       0.94      0.65      0.77        26

    accuracy                           0.81       120
   macro avg       0.86      0.65      0.71       120
weighted avg       0.83      0.81      0.79       120

In [55]:
#XGBoost
from xgboost import XGBRegressor
xgr = XGBRegressor()
xgr.fit(x_train, y_train_qual)
xgr_pred = xgr.predict(x_val)
mae = mean_absolute_error(y_val_qual, xgr_pred)
mse = mean_squared_error(y_val_qual, xgr_pred)
print('MAE: %d' %mae)
print('MSE: %d' %mse)
print(r2_score(y_val_qual, xgr_pred))

[09:11:16] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
MAE: 0
MSE: 0
0.7148558538330303

In [56]:
cq_xg = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))
cq_preds = cq_rf.predict(pd.DataFrame(xgr_pred))
from sklearn.metrics import classification_report
print(classification_report(y_val_cl, cq_preds))

<ipython-input-56-4c85d8d2732c>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  cq_xg = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67        18
           1       0.82      0.96      0.88        76
           2       0.86      0.73      0.79        26

    accuracy                           0.84       120
   macro avg       0.89      0.73      0.78       120
weighted avg       0.86      0.84      0.83       120

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(