In [1]:
#get_dummies + PCA

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import random
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [4]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(7) # Seed 고정

In [5]:
import pandas as pd
train = pd.read_csv('/content/drive/MyDrive/LG/train.csv')
test = pd.read_csv('/content/drive/MyDrive/LG/test.csv')

In [6]:
train=train.fillna(0)
test=test.fillna(0)

In [7]:
train_x = train.drop(columns=['PRODUCT_ID','Y_Class','Y_Quality','TIMESTAMP'])
test_x = test.drop(columns=['PRODUCT_ID','TIMESTAMP'])
train_x_num = train_x.filter(regex='X')
test_x_num = test_x.filter(regex='X')
#min-max-scaling이 더 나을듯
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(train_x_num)
train_x_num_scaled = scaler.transform(train_x_num)
test_x_num_scaled = scaler.transform(test_x_num)
train_x_num_scaled = pd.DataFrame(train_x_num_scaled)
test_x_num_scaled = pd.DataFrame(test_x_num_scaled)

In [8]:
train_x_num_scaled

,0,1,2,3,4,5,6,7,8,9,...,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874
0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.653054,0.595543,0.538984,0.568830,0.975172,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.645584,0.623653,0.727032,0.589688,0.909718,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.650564,0.533790,0.703029,0.609544,0.982445,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.626494,0.570492,0.863599,0.510262,0.900063,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.642430,0.610108,0.776858,0.552144,0.965141,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,0.019417,0.931373,0.0,1.0,0.909091,0.0,0.806452,0.909091,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
594,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.821215,0.772939,0.842410,0.919406,0.833730,1.0,0.0,0.0,0.0,0.0
595,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
596,0.388350,0.921569,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
597,0.203883,0.852941,0.0,1.0,0.909091,0.0,0.983871,0.909091,1.000000,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

In [9]:
test_x_num_scaled

,0,1,2,3,4,5,6,7,8,9,...,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874
0,0.019417,0.921569,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.019417,0.911765,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.019417,0.931373,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,0.019417,0.892157,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
306,0.019417,0.941176,0.0,1.0,1.000000,0.0,0.725806,0.909091,0.596154,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
307,0.019417,0.892157,0.0,1.0,0.909091,0.0,0.806452,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
308,0.019417,0.931373,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309,0.019417,0.852941,0.0,1.0,0.909091,0.0,0.822581,0.909091,1.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
cat_encoding = pd.get_dummies(train_x[['LINE','PRODUCT_CODE']])
cat_encoding_test = pd.get_dummies(test_x[['LINE','PRODUCT_CODE']])
train_x_prep = train_x_num_scaled.join(cat_encoding)
test_x_prep = test_x_num_scaled.join(cat_encoding_test)

In [11]:
train_x_prep.head()

,0,1,2,3,4,5,6,7,8,9,...,2874,LINE_T010305,LINE_T010306,LINE_T050304,LINE_T050307,LINE_T100304,LINE_T100306,PRODUCT_CODE_A_31,PRODUCT_CODE_O_31,PRODUCT_CODE_T_31
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,0,0,0,1,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,1,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,0,0,0,1,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,1,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,0,0,0,1,0,0

In [12]:
train_y = train['Y_Quality']

In [23]:
#주성분분석(젠부)

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components=598)
pca_array = pca.fit_transform(train_x_prep)
pca_df = pd.DataFrame(pca_array)
pca_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

,0,1,2,3,4,5,6,7,8,9,...,588,589,590,591,592,593,594,595,596,597
0,25.027973,14.100058,-7.144588,0.017018,-1.859462,-3.874877,0.047670,-0.143343,0.758289,-2.070741,...,1.268140e-08,3.449203e-09,1.984059e-08,5.867149e-09,-1.895708e-09,-1.794996e-10,-2.389348e-09,2.030665e-09,-8.910828e-10,6.798390e-15
1,25.524763,14.929569,-8.126228,0.017041,4.668672,-0.617491,0.056062,1.086905,-0.200412,-0.559235,...,-7.007744e-10,-1.906106e-10,-1.096458e-09,-3.242496e-10,1.047686e-10,9.920352e-12,1.320550e-10,-1.122336e-10,4.925091e-11,6.798390e-15
2,25.077096,14.060148,-7.170179,0.015117,-1.753432,-3.823965,0.051059,-0.183840,0.733692,-1.918878,...,-1.966789e-08,-5.349460e-09,-3.077133e-08,-9.099535e-09,2.940111e-09,2.783914e-10,3.705718e-09,-3.149426e-09,1.382012e-09,6.798390e-15
3,25.471308,14.840979,-7.947625,0.017023,4.489835,-0.741023,0.059233,1.151991,-0.171768,-0.739668,...,-2.481258e-08,-6.748795e-09,-3.882072e-08,-1.147991e-08,3.709231e-09,3.512179e-10,4.675138e-09,-3.973330e-09,1.743558e-09,6.798390e-15
4,25.022491,14.050860,-7.212634,0.016684,-1.757404,-3.885891,0.053505,-0.011705,0.681319,-2.160656,...,-1.116486e-08,-3.036722e-09,-1.746792e-08,-5.165518e-09,1.669007e-09,1.580339e-10,2.103616e-09,-1.787827e-09,7.845225e-10,6.798390e-15

In [24]:
result = pd.DataFrame({'설명가능한 분산 비율(고윳값)':pca.explained_variance_, '기여율':pca.explained_variance_ratio_})
result['누적기여율']=result['기여율'].cumsum()
result

     설명가능한 분산 비율(고윳값)           기여율     누적기여율
0        2.347462e+02  6.903495e-01  0.690349
1        7.417295e+01  2.181303e-01  0.908480
2        1.532662e+01  4.507303e-02  0.953553
3        1.908176e+00  5.611628e-03  0.959164
4        1.539023e+00  4.526010e-03  0.963690
..                ...           ...       ...
593      4.283173e-09  1.259610e-11  1.000000
594      3.115511e-09  9.162199e-12  1.000000
595      2.139143e-09  6.290863e-12  1.000000
596      8.178662e-10  2.405208e-12  1.000000
597      4.629552e-29  1.361474e-31  1.000000

[598 rows x 3 columns]

In [25]:
#3개만하자
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
train_num_pca = pca.fit_transform(train_x_prep)
train_pca=pd.DataFrame(data=train_num_pca)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [26]:
train_pca

             0          1          2
0    25.027973  14.100058  -7.144588
1    25.524763  14.929569  -8.126228
2    25.077096  14.060148  -7.170179
3    25.471308  14.840979  -7.947625
4    25.022491  14.050860  -7.212634
..         ...        ...        ...
593 -12.601979   1.757324  -0.052353
594  21.309284   7.057265  10.128221
595  21.136848   6.591512   9.864859
596 -12.589343   1.751204  -0.050996
597 -12.520105   1.721428  -0.047384

[598 rows x 3 columns]

In [27]:
test_num_pca = pca.transform(test_x_prep)
test_pca=pd.DataFrame(data=test_num_pca)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [28]:
test_pca

             0          1         2
0   -12.554223   1.736340 -0.049411
1   -12.540814   1.729794 -0.047926
2   -12.588264   1.750654 -0.050858
3    12.118824 -14.623093 -0.910130
4    12.090527 -14.605638 -0.922303
..         ...        ...       ...
305 -12.652142   1.779332 -0.055413
306 -12.571661   1.743387 -0.049859
307 -12.645764   1.776560 -0.055049
308 -12.578872   1.747184 -0.050943
309 -12.731876   1.814423 -0.060377

[310 rows x 3 columns]

In [32]:
train_y = train[['Y_Quality','Y_Class']]

In [49]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(train_pca, train_y, test_size = 0.1, random_state = 7)

In [50]:
y_train_qual = y_train['Y_Quality']
y_val_qual = y_val['Y_Quality']
y_train_cl = y_train['Y_Class']
y_val_cl = y_val['Y_Class']

In [51]:
#RandomforestRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
rfr = RandomForestRegressor()
rfr.fit(x_train, y_train_qual)
rfr_pred = rfr.predict(x_val)
mae = mean_absolute_error(y_val_qual, rfr_pred)
mse = mean_squared_error(y_val_qual, rfr_pred)
print('MAE: %d' %mae)
print('MSE: %d' %mse)
print(r2_score(y_val_qual, rfr_pred))

MAE: 0
MSE: 0
-0.0814906231181165

In [52]:
# train_class = pd.DataFrame(train['Y_Class'])
# train_qual = pd.DataFrame(train['Y_Quality'])
cq_rf = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))

<ipython-input-52-367135154b13>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  cq_rf = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))

In [53]:
cq_preds = cq_rf.predict(pd.DataFrame(rfr_pred))

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_val_cl, cq_preds))

              precision    recall  f1-score   support

           0       0.50      0.10      0.17        10
           1       0.66      0.97      0.79        36
           2       0.60      0.21      0.32        14

    accuracy                           0.65        60
   macro avg       0.59      0.43      0.42        60
weighted avg       0.62      0.65      0.57        60

In [55]:
#XGBoost
from xgboost import XGBRegressor
xgr = XGBRegressor()
xgr.fit(x_train, y_train_qual)
xgr_pred = xgr.predict(x_val)
mae = mean_absolute_error(y_val_qual, xgr_pred)
mse = mean_squared_error(y_val_qual, xgr_pred)
print('MAE: %d' %mae)
print('MSE: %d' %mse)
print(r2_score(y_val_qual, xgr_pred))

[08:58:11] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
MAE: 0
MSE: 0
-0.08833981864371787

In [56]:
cq_xg = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))
cq_preds = cq_rf.predict(pd.DataFrame(xgr_pred))
from sklearn.metrics import classification_report
print(classification_report(y_val_cl, cq_preds))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.62      0.97      0.76        36
           2       0.67      0.14      0.24        14

    accuracy                           0.62        60
   macro avg       0.43      0.37      0.33        60
weighted avg       0.53      0.62      0.51        60

<ipython-input-56-4c85d8d2732c>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  cq_xg = RandomForestClassifier(random_state=7).fit(pd.DataFrame(y_train_qual), pd.DataFrame(y_train_cl))
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(